version: '3'
services:
  postgresql:
    image: postgres
    container_name: backend
    ports:
      - '5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DATABASE=backendshop
    command: postgres
    restart: always
